### ISSUE TITLE
Passhole ask every time for password to access database

### ISSUE THREAD

**Issue by ReneFroger** [Evidlo/passhole#27]
First, thanks for creating and sharing such a nicely CLI!

My issue when I wanted to access my password entries with `ph type dmenu`, it will ask me for the master password first. Okay, then choose entry. But 10 seconds later I want to select another entry. Then I need to fill my master password again.`

Is there a way to tell there is no need to use master password if this is given in, let's say, half hour ago?

**Comment by Evidlo** [comment]
What version are you using?

**Comment by ReneFroger** [comment]
1.9.post1, installed via pip. 

However, I noticed when I'm filling a password for first time and get access to it, then it doesn't matter when I'm filling a wrong password when he asks again for password, I still get dmenu popping up with my Passhole entries after filling wrong password. The only condition is that my password is right before in a short time (I guess in 15 minutes)?

**Comment by ReneFroger** [comment]
Unfortunately still same issue with newer version of passhole, `1.9.post2`, installed via pip.

**Comment by Evidlo** [comment]
This should be fixed now.

**Comment by ReneFroger** [comment]
Really? I noticed PH is still on version 1.9.2 which I have installed here.

**Comment by Evidlo** [comment]
I just tested this on a fresh system and I'm not seeing this anymore.

```
[evan@blackbox passhole] make docker_debian
...
root@3a9bf169547c:/home/passhole# ph --version
1.9.4

root@3a9bf169547c:/home/passhole# ph init
Database name (no spaces): passhole
Desired database path: /root/.local/passhole/passhole.kdbx
Password protect database? (Y/n): 
Password: 
Confirm: 
Use a keyfile? (Y/n): n
Creating database at /root/.local/passhole/passhole.kdbx
Creating config at /root/.config/passhole.ini

root@3a9bf169547c:/home/passhole# ph add hello -w
Enter database password: 
Username: evidlo
URL: example.com

root@3a9bf169547c:/home/passhole# ph add foobar -w
Username: evidlo
URL: example.com
```

**Comment by ReneFroger** [comment]
I mean with my comment that the version was still the same version, but you're right. I don't see this issue anymore (even with the same version 1.9.2 which is somewhat weird).

But thanks for helping, it's greatly appreciated! 

This issue can be marked as closed.
